# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}} # specify the wiki repo name here.
        

      - name: Install Dependencies to build pdf's.
        run: |
          sudo apt-get install pandoc=2.5-3build2 weasyprint=51-2
      - name: Make page directory
        run: |
          mkdir -p docs
      - name: Clean up former pages
        run: |
          rm -f docs/*
      - name: Build pdf's and home page
        run: |
          page_setup/build.sh $(pwd)/docs "https://cthulhu-jesus.github.io/fiction/"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git status
          git commit -m "Add changes"
      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}    # specify the wiki repo and push the update.
          github_token: ${{ secrets.GITHUB_TOKEN }}
